dist: xenial   # required for Python >= 3.7
language: python
python:
 - "3.6"
 - "3.7"
 - "3.8-dev"
 - "pypy3.5"
install:
 - python setup.py install
 - python setup.py test 
script: py.test --assert=plain

